# calib_location = 
#   0 = RS2_CALIB_LOCATION_EEPROM
#   1 = RS2_CALIB_LOCATION_FLASH
#   2 = RS2_CALIB_LOCATION_RAM (default)
uint8 calib_location 2
---
bool success
string error_message
string safety_interface_config
